'use strict';
const width = 7;
const height = 4;
const area = width * height;
console.log('value of area: ', area);
console.log('typeof area: ', typeof area);
const bill = 30;
const payment = 50;
const change = payment - bill;
console.log('value of change: ', change);
console.log('typeof change: ', typeof change);
const quizzes = 45;
const midterm = 25;
const final = 80;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade: ' + grade);
console.log('typeof grade: ' + typeof grade);
const firstName = 'Ruqaiya';
const lastName = 'Electricwala';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName: ' + fullName);
console.log('typeof fullName: ' + typeof fullName);
const pH = 5.5;
const isAcidic = pH < 7;
console.log('value of isAcidic: ' + isAcidic);
console.log('typeof isAcidic: ' + typeof isAcidic);
const headCount = 18;
const isSparta = headCount === 300;
console.log('value of isSparta: ' + isSparta);
console.log('typeof isSparta: ' + typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('value of nickname: ' + motto);
console.log('typeof nickname: ' + typeof motto);
